add flags
kosimovsky/tricMe pull request #8
Opened 2022-08-02 23:07 UTC by kosimovsky

Добавил флаги серверу и агенту, изменил чтение и использование конфигурации

2022-08-09 19:57 UTC, capsulated requested changes
Много мелких замечаний. Необходимо исправить и я ещё раз полностью всё проверю.

2022-08-09 19:57 UTC, capsulated commented on cmd/agent/main.go
> +	m, _ := repo.NewMiner(&repo.Source{Resources: viper.GetString("metricstype")})
Лучше не оставлять пустые ошибки. Если только в процессе отладки, но в комите так лучше не делать.

2022-08-09 19:57 UTC, capsulated commented on cmd/agent/main.go
`if err := newAgent.RunWithSerialized(); err != nil {`
Повторно создаётся переменная с именем, которое уже существует. Либо имя другое выбрать, либо переиспользовать переменную **err**

2022-08-09 19:57 UTC, capsulated commented on cmd/server/main.go
>  		_ = fmt.Errorf("error while reading config file %v", err.Error())
Уже писал: странная конструкция ))  fmt.Errorf возвращает **err**.

2022-08-09 19:57 UTC, capsulated commented on cmd/server/main.go
> +	store, _ := storage.NewStorage(&storage.Storage{StorageType: viper.GetString("storage")})
**err** не обработанный лучше не оставлять. Нужно проверить, вывести и обработать.

2022-08-09 19:57 UTC, capsulated commented on cmd/server/main.go
>  		go func() {
Такое из cmd обязательно нужно перенести в пакет агента. И в зависимости от конфигов уже реализовывать логику внутри воркера (агента в нашем случае).

2022-08-09 19:57 UTC, capsulated commented on cmd/server/main.go
> -	if viper.GetBool("server.debug") {
Все действия с конфигами необходимо перенести в отдельный пакет. А потом всем другим пакетам передавать в конструкторе либо весь конфиг, либо часть, которая относиться к пакету. Либо несколько конфигов. Либо Один общий и создавать структуру с всраиванием/композицией для каждого из частных случаев.

2022-08-09 19:57 UTC, capsulated commented on internal/agent/agent_runtime.go
>  func urlGenerator(conf config, m map[string]gauge) (urls []string) {
fmt.Sprintf будет лучше смотреться в `server := "http://" + conf.address + "/update/"` )))

2022-08-09 19:57 UTC, capsulated commented on internal/agent/agent_runtime.go
>  func urlGenerator(conf config, m map[string]gauge) (urls []string) {
Также, дублируется операция. Может строку составлять в конструкторе? А функции привязать к структуре, чтобы они были методами? 

Если они дублируются в разных структурах, то можно воспользоваться **встраиванием** или **embedding**
https://medium.com/german-gorelkin/embedding-in-go-6739e46c1be1

2022-08-09 19:57 UTC, capsulated commented on internal/agent/agent_runtime.go
>  func newConfig() *config {
newConfig() приватная функция-конструктор?

Лучше сделать конструктор конфига в спец пакете конфига )

2022-08-09 19:57 UTC, capsulated commented on internal/agent/agent_runtime.go
>  func urlGenerator(conf config, m map[string]gauge) (urls []string) {
И функции, не привязанные к структуре, лучше переместить либо в отдельный пакет, либо привязать к какой-то структуре.

2022-08-10 07:16 UTC, kosimovsky commented on internal/agent/agent_runtime.go
>  func urlGenerator(conf config, m map[string]gauge) (urls []string) {
Часть  кода осталась от реализации прошлых инкрементов, не используется, удалил
создание url изменил на Sprintf

2022-08-10 07:16 UTC, kosimovsky commented on internal/agent/agent_runtime.go
>  func newConfig() *config {
В коде сервера переделал, а в агенте осталось, переделал

2022-08-10 07:18 UTC, kosimovsky commented on cmd/server/main.go
> -	if viper.GetBool("server.debug") {
в последнем инкременте я это уже убрал, работу с конфигами перенес в отдельный пакет

2022-08-10 07:20 UTC, kosimovsky commented on cmd/server/main.go
>  		go func() {
это уже вынесено в отдельный пакет в реализации 8-го инкремента

2022-08-10 07:21 UTC, kosimovsky commented on cmd/server/main.go
> +	store, _ := storage.NewStorage(&storage.Storage{StorageType: viper.GetString("storage")})
исправил, добавил обработку ошибки

2022-08-10 07:24 UTC, kosimovsky commented on cmd/agent/main.go
Исправил оператор, переиспользую переменную

2022-08-10 07:28 UTC, kosimovsky commented on cmd/server/main.go
>  		_ = fmt.Errorf("error while reading config file %v", err.Error())
исправил, заменил на Printf

2022-08-10 07:29 UTC, kosimovsky commented on cmd/agent/main.go
> +	m, _ := repo.NewMiner(&repo.Source{Resources: viper.GetString("metricstype")})
Добавил обработку ошибки

2022-08-15 20:54 UTC, merged