gzip handlers added
kosimovsky/tricMe pull request #9
Opened 2022-08-05 21:10 UTC by kosimovsky

тест Accept-Encoding

2022-08-10 23:28 UTC, capsulated requested changes
Прокомментировал

Дублируется файлик темплейта start_page.html 
Наверное, один лишний

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
>  	logrus.New()
Логгер по-хорошему нужно вынести в отдельный пакет

2022-08-10 23:28 UTC, capsulated commented on internal/storage/toMemory.go
> +}
`internal/test/test.json`
пустой файл) не нужно такое в репозиторий пушить))

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
>  		_ = fmt.Errorf("error while reading config file %v", err.Error())
Возвращается fmt.Errorf возвращает error. И возвращает в пустой индикатор переменной. Может просто сообщение вывести об ошибке и выйти? Или панику?

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
> +	store, _ := storage.NewStorage(&storage.Storage{StorageType: c.Storage})
Ошибки нужно обрабатывать, даже если это уже надоело )))

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
> +		fmt.Printf("error while reading config file %s", err.Error())
Так error-то не выведется никуда. 
Ещё остановить выполнение нужно, способ любой:

- os.Exit(1)
- panic(err)
- log.Fatalf()
- ...

Да и можно перед чтением конфига создать логгер , если ему в конструкторе не нужны данные из конфига. Но если в конфиге есть параметры для логгера, то уже нет

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
> +	c := config.AgentConfig()
Конструкторы лучше обзывать c New-префиксом, `config.NewAgentConfig()`

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
> +	agentLog.Default(c.Logfile)
Установку файла можно в конструктор перенести, не создавая дополнительный метод. В сервере вроде также. Поэтому **c.Logfile** можно передавать в параметр конструктора.

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
> +		agentLog.Error(err)
Если не остановится выполнение, будут непредвиденные события. **logrus.Error** вроде не останавливает выполнения рантайма?

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
>  	serv := service.New(m)
Этот пакет простая обёртка для request'а, может его переместить в агент? Он наследуется в единственном месте и вызывается также. Если подобной реквест будет много где имплементироваться, то смысл есть. 

А в таком случае кода получается больше и читать сложнее.

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
> +		fmt.Printf("error while reading config file %s", err.Error())
Также, не выведется и не остановится

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
> +	logMe := logger.NewLogger()
Логгер можно просто называть **logger**, чтобы везде одинаково было

2022-08-10 23:28 UTC, capsulated commented on cmd/agent/main.go
> +		agentLog.Errorf("error while running agent: %s", err.Error())
Логгер можно просто называть **logger**

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
>  		go func() {
Эти функции нужно перенести в пакет. **store**, как я понимаю?

А в **cmd** уже вызывать **go store.Метод()**. А значения тикера определять из конфига уже внутри стора.

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
>  		go func() {
Также инкапсулировать в пакет. А то очень много логики в **cmd**

2022-08-10 23:28 UTC, capsulated commented on cmd/server/main.go
>  	go func() {
Можно перенести логику в сервер, чтобы log.Fatalf вызывался в пакете. А в cmd только go srv.Run().

А создание &http.Server{ ... } внутри пакета server, нужно перенести в конструктор, а не в метод Run()

2022-08-10 23:28 UTC, capsulated commented on config/config.go
> +		_, err = fmt.Fprintln(os.Stderr, "Use serverConfig file:", viper.ConfigFileUsed())
error очень как-то сложно формируется. Проще можно, вернуть err, а вывести его в вызывающем коде. Либо константами сформировать новый err (пакет error) и вернуть в зависимости от условий.

2022-08-10 23:28 UTC, capsulated commented on config/config.go
> +type serverConfig struct {
Определение типов обычно объявляются перед методами, которые их используют. Так читать удобнее, то есть
`type Configer interface {...}`
`type serverConfig struct {...}`
`func NewServerConfig(...) *serverConfig {...}`
`func (*serverConfig) funcName1(...) {...}`
`func (*serverConfig) funcName2(...) {...}`

приблизительно

2022-08-10 23:28 UTC, capsulated commented on config/config.go
> +func AgentConfig() *agentConfig {
NewAgentConfig() желательно

2022-08-10 23:28 UTC, capsulated commented on config/config.go
> +func ServerConfig() *serverConfig {
NewServerConfig() желательно

2022-08-10 23:28 UTC, capsulated commented on internal/agent/agent_runtime.go
>  		serv: serv}
Сложно читать с плане отступов.
Примерчик:

```go
func NewAgent(serv Sender) *agent {
	dialer := &net.Dialer{
		Timeout: 30 * time.Second,
		KeepAlive: 30 * time.Second,
	}
	
	transport := &http.Transport{
		DialContext:     dialer.DialContext,
		MaxIdleConns:    30,
		IdleConnTimeout: 60 * time.Second,
	}
	
	client := http.Client{
		Timeout: 5*time.Second,
		Transport: transport,
	}
	
	return &agent{
		client: &client,
		serv: serv,
	}
}
```

и редактировать настройки потом проще)

2022-08-10 23:28 UTC, capsulated commented on internal/agent/agent_runtime.go
>  	go func() {
Вот эти функции тоже бы отдельными сделать, чтобы вызывать 
`go metrics.GenerateMetrics()`
`metrics.SendMetrics()`

2022-08-10 23:28 UTC, capsulated commented on internal/agent/agent_runtime.go
> +			t := time.NewTicker(c.Poll)
Тикер в цикле создаётся, это ок?

Лучше тикеры создать в конструкторе агента, и добавть указатели на них в самой структуре, типа того:
```go
type agent struct {
	client *http.Client
	serv   Sender
        tickerCollect  *Ticker
        tickerSend  *Ticker
}
```

как-то так...

2022-08-10 23:28 UTC, capsulated commented on internal/agent/agent_runtime.go
>  		for _, metric := range metrics.MetricsArray {
И из Run перенести всё же логику работы агента в независимые функции. 

А в Run только запуск

2022-08-10 23:28 UTC, capsulated commented on internal/handlers/handlers.go
>  func (h *Handler) MetricsRouter() *gin.Engine {
это в принципе в конструктор можно перенести

2022-08-10 23:28 UTC, capsulated commented on internal/handlers/middleware.go
>  	} else {
else по факту не нужен, так как return

if/else усложняют код

https://habr.com/ru/post/478158/

2022-08-10 23:28 UTC, capsulated commented on internal/logger/logger.go
> +func (l *logger) Default(filename string) {
Мне кажется в конструкторе будет лучше этой логике)

2022-08-10 23:28 UTC, capsulated commented on internal/logger/logger.go
> +		fmt.Fprintf(os.Stderr, "error occured opening file : %s, %s", err.Error(), filename)
А тут не остановится выполнение. Нужно возвращать err. А на стороне вызывающего вывести ошибку и либо остановить выполнение, либо продолжить

2022-08-10 23:28 UTC, capsulated commented on internal/server/server.go
>  	s.httpServer = &http.Server{
Это точно логика конструктора. А в Run только запуск должен быть

2022-08-10 23:28 UTC, capsulated commented on internal/storage/storage.go
>  	switch s.StorageType {
Ну вот, фабрика вроде получилась)

2022-08-10 23:28 UTC, capsulated commented on internal/storage/toFile.go
>  type Storer interface {
```go
type storer struct {
	file    *os.File
	encoder *json.Encoder
}
```
тогда уж просто `store` наверное?

2022-08-11 18:47 UTC, kosimovsky commented on cmd/server/main.go
>  	logrus.New()
логгер вынес

2022-08-11 18:47 UTC, kosimovsky commented on internal/storage/toMemory.go
> +}
это да, забыл выкинуть

2022-08-11 18:48 UTC, kosimovsky commented on cmd/server/main.go
>  		_ = fmt.Errorf("error while reading config file %v", err.Error())
да, переделал на панику, потому что без конфига ничего и не должно работать

2022-08-11 18:49 UTC, kosimovsky commented on cmd/server/main.go
> +	store, _ := storage.NewStorage(&storage.Storage{StorageType: c.Storage})
обработал

2022-08-11 18:49 UTC, kosimovsky commented on cmd/agent/main.go
> +		fmt.Printf("error while reading config file %s", err.Error())
в конфиге задаётся имя файла логов

2022-08-11 18:52 UTC, kosimovsky commented on cmd/agent/main.go
> +	agentLog.Default(c.Logfile)
я сделал метод Default с мыслью о том, что будет расширяться программа и в какой-то момент потребуется какой-нибудь необычный логгер, для тестов например, и для этого сделал бы новый метод

2022-08-11 18:53 UTC, kosimovsky commented on cmd/agent/main.go
> +		agentLog.Error(err)
исправил, теперь будет останавливаться и возвращать ненулевой статус-код

2022-08-11 18:54 UTC, kosimovsky commented on cmd/agent/main.go
>  	serv := service.New(m)
да, изначально нагородил лишнюю сущность, так и осталась
убрал совсем пакет service и изменил немного инициализацию агента

2022-08-11 18:54 UTC, kosimovsky commented on cmd/server/main.go
> +		fmt.Printf("error while reading config file %s", err.Error())
исправил, как и в агенте

2022-08-11 18:55 UTC, kosimovsky commented on cmd/server/main.go
> +	logMe := logger.NewLogger()
убрал дефолтный метод логгера и изменил имя

2022-08-11 18:55 UTC, kosimovsky commented on cmd/agent/main.go
> +		agentLog.Errorf("error while running agent: %s", err.Error())
убрал дефолтный метод логгера и изменил имя

2022-08-11 18:56 UTC, kosimovsky commented on cmd/agent/main.go
> +	c := config.AgentConfig()
изменил обзывание конструкторов сервера и агента)

2022-08-14 16:18 UTC, kosimovsky commented on cmd/server/main.go
>  		go func() {
перенес из cmd

2022-08-14 16:18 UTC, kosimovsky commented on cmd/server/main.go
>  		go func() {
перенес из cmd

2022-08-14 16:23 UTC, kosimovsky commented on cmd/server/main.go
>  	go func() {
Перенес логику с Fatalf в пакет сервера, мэйн стал компактнее 
конструктор сервера тоже переделал

2022-08-14 16:27 UTC, kosimovsky commented on config/config.go
> +		_, err = fmt.Fprintln(os.Stderr, "Use serverConfig file:", viper.ConfigFileUsed())
переделал на return в вызывающий код

2022-08-14 16:28 UTC, kosimovsky commented on config/config.go
> +func AgentConfig() *agentConfig {
изменил имя

2022-08-14 16:29 UTC, kosimovsky commented on config/config.go
> +func ServerConfig() *serverConfig {
изменил имя конструктора

2022-08-14 16:37 UTC, kosimovsky commented on internal/agent/agent_runtime.go
>  		serv: serv}
Да, здесь не читаемо было, поправил.
Спасибо!

2022-08-14 18:06 UTC, kosimovsky commented on internal/agent/agent_runtime.go
>  	go func() {
1 задачу выполнил, 2-ю нужно переделывать на каналы видимо, в текущем виде реализовать не удалось
метрики не отправляются, агент блокируется
подумаю над решением

2022-08-14 18:27 UTC, kosimovsky commented on internal/agent/agent_runtime.go
> +			t := time.NewTicker(c.Poll)
это было в одной из первых версий, совсем плохих

2022-08-14 18:31 UTC, kosimovsky commented on internal/handlers/middleware.go
>  	} else {
да, исправил

2022-08-14 18:48 UTC, kosimovsky commented on internal/server/server.go
>  	s.httpServer = &http.Server{
перенес в конструктор

2022-08-14 18:48 UTC, kosimovsky commented on internal/logger/logger.go
> +		fmt.Fprintf(os.Stderr, "error occured opening file : %s, %s", err.Error(), filename)
исправил

2022-08-15 20:38 UTC, capsulated approved these changes
Оч классно теперь организован код. Будет удобно читать и исправлять в будущем. 

Есть совсем небольшие замечания:
- структура **storage** не используется, стререть
- разделять строки можно пустыми на логические блоки, также для более удобного чтения (пример, как я обычно разделяю, разделяю):
<img width="690" alt="Screenshot 2022-08-15 at 23 25 06" src="https://user-images.githubusercontent.com/10791403/184713270-049fd122-c59d-435d-a4d0-6de5bea57f8e.png">
- в пакете handlers висит одинокая функция **convert**, пристроить бы её куда нибудь ))
- в пакете handlers  updateGauge, updateCounter пустые строки в начале метода))) Мелочь, конечно, но прям оч сильно выделяется при чтении 😅
- в errors висит неиспользуемый errorsResponseWithStatusCode, удалить наверное?

А, и самое главное, в конфиге отделять New от Init лишнее. Init перенести в конструктор - и будет просто пушка)

2022-08-15 20:38 UTC, capsulated commented on cmd/agent/main.go
> +	c := config.NewAgentConfig()
Всё, в принципе, оч классно читаемо, но Init и New можно объединить. 

То есть, в **NewAgentConfig** мы инициализируем конфиги и возвращаем структуру. И будет ващпе идеально 😄

2022-08-15 20:38 UTC, capsulated commented on internal/repo/repository.go
> +type source struct {
вообще не используется, кажется структура не нужна

2022-08-15 20:50 UTC, kosimovsky commented on internal/repo/repository.go
> +type source struct {
структуры storage и source использовались в предыдущих версиях), забыл затереть
функция convert была тоже написана для не json версии агента и используется в методах handler'a, а они в свою очередь остались в роутере, по сути не нужны, удалю в следующих инкрементах
инициализацию конфига объёдиню в конструктор также
Спасибо!

2022-08-15 20:50 UTC, kosimovsky commented on cmd/agent/main.go
> +	c := config.NewAgentConfig()
это переделаю обязательно

2022-08-15 20:53 UTC, merged